# Generated by Django 3.2.5 on 2021-08-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_username_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='prof_image',
            field=models.ImageField(blank=True, default='/images/badge/anon.jpg', null=True, upload_to='badge/', verbose_name='Аватар'),
        ),
    ]
