# Generated by Django 3.2.5 on 2021-08-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='prof_image',
            field=models.ImageField(default='badge/anon.jpg', upload_to='badge/', verbose_name='Аватар'),
        ),
    ]
