# Generated by Django 3.2.6 on 2021-08-16 09:48

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='prof_image',
            field=models.ImageField(default='badge/anon.jpg', upload_to=account.models.get_prof_image_path, verbose_name='Аватар'),
        ),
    ]
