# Generated by Django 3.2.5 on 2021-08-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
