# Generated by Django 3.2.6 on 2021-08-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_rename_author_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='read_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Читабельное название'),
        ),
    ]
